language: node_js

node_js:
  - 'stable'
  - '6'
  - '4'

sudo: false

install:
  - npm install
  - npm install karma
  - npm install karma-cli
  - npm install karma-chrome-launcher

cache:
  directories:
    - node_modules
