language: node_js

node_js:
  - 'stable'
  - '6'
  - '4'

sudo: false

install:
  - npm install
  - npm install karma -g
  - npm install karma-cli -g
  - npm install karma-chrome-launcher -g

cache:
  directories:
    - node_modules
