# Node.js

# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

jobs:
  - job: Windows
    displayName: 'Build Job for JS (VS2019)'
    pool:
      vmImage: 'windows-2019'
    steps:
      - template: build/sdl-tasks.yml
      - task: DownloadPipelineArtifact@2
        inputs:
          buildType: 'specific'
          project: 'a7934fdd-dcde-4492-a406-7fad6ac00e17'
          definition: '1758'
          specificBuildWithTriggering: true
          buildVersionToDownload: 'latest'
          allowFailedBuilds: true
          targetPath: '$(Pipeline.Workspace)/artifacts'
      - task: AzureKeyVault@2
        inputs:
          azureSubscription: 'MSIDLABKeyVault'
          KeyVaultName: 'ADALTestInfo'
          SecretsFilter: 'MSALJSGITHUB'
          RunAsPreJob: true
      - task: CmdLine@2
        inputs:
          script: 'ls -la $(Pipeline.Workspace)/artifacts'
