#################################################################################
#                      OneBranch Pipelines - PR Build                           #
# This pipeline was created by EasyStart from a sample located at:              #
#   https://aka.ms/obpipelines/easystart/samples                                #
# Documentation:  https://aka.ms/obpipelines                                    #
# Yaml Schema:    https://aka.ms/obpipelines/yaml/schema                        #
# Retail Tasks:   https://aka.ms/obpipelines/tasks                              #
# Support:        https://aka.ms/onebranchsup                                   #
#################################################################################

trigger: none # https://aka.ms/obpipelines/triggers

parameters: # parameters are shown up in ADO UI in a build queue time
- name: 'debug'
  displayName: 'Enable debug output'
  type: boolean
  default: false

variables:
  CDP_DEFINITION_BUILD_COUNT: $[counter('', 0)] # needed for onebranch.pipeline.version task https://aka.ms/obpipelines/versioning
  system.debug: ${{ parameters.debug }}
  ENABLE_PRS_DELAYSIGN: 0
  ROOT: $(Build.SourcesDirectory)
  REPOROOT: $(Build.SourcesDirectory)
  OUTPUTROOT: $(REPOROOT)\out
  NUGET_XMLDOC_MODE: none

  LinuxContainerImage: 'onebranch.azurecr.io/linux/ubuntu-2004:latest' # Docker image which is used to build the project https://aka.ms/obpipelines/containers

resources:
  repositories: 
    - repository: templates
      type: git
      name: OneBranch.Pipelines/GovernedTemplates
      ref: refs/heads/main

extends:
  template: v2/OneBranch.NonOfficial.CrossPlat.yml@templates # https://aka.ms/obpipelines/templates
  parameters:
    globalSdl: # https://aka.ms/obpipelines/sdl
      tsa:
        enabled: false # onebranch publish all sdl results to TSA. If TSA is disabled all SDL tools will forced into 'break' build mode.
      # credscan:
      #   suppressionsFile: $(Build.SourcesDirectory)\.config\CredScanSuppressions.json
      binskim:
        break: true # always break the build on binskim issues. You can disable it by setting to 'false'
      policheck:
        break: true # always break the build on policheck issues. You can disable it by setting to 'false'
      # suppression:
      #   suppressionFile: $(Build.SourcesDirectory)\.gdn\global.gdnsuppress

    stages:
    - stage: pre_release
      displayName: Pre-Publish
      jobs:
        - job: filter
          pool:
            type: linux
          variables:
            repoName: 'msal-javascript-internal'
            ob_outputDirectory: '$(REPOROOT)/${{ variables.repoName }}/out' # this directory is uploaded to pipeline artifacts, reddog and cloudvault. More info at https://aka.ms/obpipelines/artifacts
            ob_sdl_binskim_break: true # https://aka.ms/obpipelines/sdl
          steps:
          - task: ShellScript@2
            inputs:
              scriptPath: ".pipelines/scripts/prepublish.sh"
            name: filter

    - stage: build_and_release
      dependsOn: pre_release
      displayName: 'Publish'
      variables:
        publishMsalCommon: $[ stageDependencies.pre_release.filter.outputs['filter.publishMsalCommon'] ]
        publishMsalBrowser: $[ stageDependencies.pre_release.filter.outputs['filter.publishMsalBrowser'] ]
        publishMsalNode: $[ stageDependencies.pre_release.filter.outputs['filter.publishMsalNode'] ]
        publishMsalReact: $[ stageDependencies.pre_release.filter.outputs['filter.publishMsalReact'] ]
        publishMsalAngular: $[ stageDependencies.pre_release.filter.outputs['filter.publishMsalAngular'] ]
        publishMsalCore: $[ stageDependencies.pre_release.filter.outputs['filter.publishMsalCore'] ]
        publishNodeTokenValidation: $[ stageDependencies.pre_release.filter.outputs['filter.publishNodeTokenValidation`'] ]
      jobs:
      # Release MSAL Core
        - template: .pipelines/custom-templates/publish-template.yml@self
          parameters:
            jobName: 'release_msal_core'
            path: 'lib'
            libName: 'msal-core'
            cdn: true
            ${{ if eq($[variables.publishMsalCore], true) }}:
              publish: true
      # Release MSAL Common
        - template: .pipelines/custom-templates/publish-template.yml@self
          parameters:
            jobName: 'release_msal_common'
            path: 'lib'
            libName: 'msal-common'
            cdn: false
            publish: $(variables.publishMsalCore)
      # Release MSAL Browser
        - template: .pipelines/custom-templates/publish-template.yml@self
          parameters:
            jobName: 'release_msal_browser'
            path: 'lib'
            libName: 'msal-browser'
            dependsOn: 'release_msal_common'
            cdn: true
            ${{ if eq(variables.publishMsalBrowser, true) }}:
              publish: true
      # Release MSAL Node
        - template: .pipelines/custom-templates/publish-template.yml@self
          parameters:
            jobName: 'release_msal_node'
            path: 'lib'
            libName: 'msal-node'
            dependsOn: 'release_msal_common'
            cdn: false
            ${{ if eq(variables.publishMsalNode, true) }}:
              publish: true
      # Release MSAL React
        - template: .pipelines/custom-templates/publish-template.yml@self
          parameters:
            jobName: 'release_msal_react'
            path: 'lib'
            libName: 'msal-react'
            dependsOn: 'release_msal_browser'
            cdn: false
            ${{ if eq(variables.publishMsalReact, true) }}:
              publish: true
      # Release MSAL Angular
        - template: .pipelines/custom-templates/publish-template.yml@self
          parameters:
            jobName: 'release_msal_angular'
            path: 'lib'
            libName: 'msal-angular'
            dependsOn: 'release_msal_browser'
            cdn: false
            ${{ if eq(variables.publishMsalAngular, true) }}:
              publish: true
        - template: .pipelines/custom-templates/publish-template.yml@self
          parameters:
            jobName: 'release_msal_node_extensions'
            path: 'extensions'
            libName: 'msal-node-extensions'
            cdn: false
            ${{ if eq(variables.publishMsalNodeExtensions, true) }}:
              publish: true