# Node.js

# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript
pool:
  vmImage: ubuntu-latest
stages:
  - stage: update_github_repo
    displayName: 'Update GitHub Repository' 
    jobs:
      # Update each package with artifacts from release
      - template: custom-templates/post-publish-template.yml
        parameters:
          libName: 'core'
          cdn: true
      - template: custom-templates/post-publish-template.yml
        parameters:
          libName: 'common'
      - template: custom-templates/post-publish-template.yml
        parameters:
          libName: 'browser'
      - template: custom-templates/post-publish-template.yml
        parameters:
          libName: 'node'
      - template: custom-templates/post-publish-template.yml
        parameters:
          libName: 'react'
      - template: custom-templates/post-publish-template.yml
        parameters:
          libName: 'angular'
      - template: custom-templates/post-publish-template.yml
        parameters:
          libName: 'node-extensions'
      job: publish_updates_to_github
        steps:
          # Create Pull Request from post-release-month-year to dev 
          - task: Npm@1
            displayName: Install release scripts dependencies
            condition: always()
            inputs:
              command: 'custom'
              customCommand: 'ci'
              workingDirectory: 'release-scripts/'
          - task: CmdLine@2
            displayName: 'Get Release Date'
            condition: always()
            inputs:
              script: echo "##vso[task.setvariable variable=releaseDate]$(node getReleaseDate.js)"
              workingDirectory: 'release-scripts/'
            env:
              TZ: "America/Los_Angeles"
          - task: CmdLine@2
            displayName: 'Get branch'
            condition: always()
            inputs:
              script: echo "##vso[task.setvariable variable=branch]$(node getReleaseDate.js -branch)"
              workingDirectory: 'release-scripts/'
            env:
              TZ: "America/Los_Angeles"
          - task: CmdLine@2
            displayName: 'Commit Changes'
            condition: always()
            inputs:
              script: |
                git config --global user.email "release@msaljs.com"
                git config --global user.name "Release Pipeline"
                git checkout -b post-release-$(branch)
                git add .
                git commit -m "$(releaseDate) Post Release"
                git remote add upstream https://${GITHUBTOKEN}@github.com/AzureAD/microsoft-authentication-library-for-js.git
                git pull upstream post-release-$(branch)
                git push upstream post-release-$(branch)
            env:
              GITHUBTOKEN: $(MSALJSGITHUB)
          - script: node pullRequest.js --titleDate=$(releaseDate) --branch=post-release-$(branch)
            displayName: "Post Release Pull Request"
            condition: always()
            workingDirectory: 'release-scripts/'
            name: post_release_pull_request
            env:
              GITHUBTOKEN: $(MSALJSGITHUB)