# Bump package version numbers and create a release branch
name: Automate Release

on:
  push:
    branches:
      - dev

jobs:
  release:
    name: Bump versions and create changelog PR --updation
    runs-on: ubuntu-latest
    steps:
      # Check-out repo
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # Check out onto desired branch or tag to create release from
      - name: Checkout tag/branch
        run: git checkout ${{ github.event.inputs.branch }}

      # Push changes
      - name: Push branch
        run: git push --set-upstream origin ${{ steps.version.outputs.version }}