# Bump package version numbers and create a release branch
name: Automate Release

on:
  push:
    branches:
      - dev
  workflow_dispatch:
    inputs:
      versionName:
        description: 'Name of version '
        required: true
      versionCode:
        description: 'Version #'
        required: true

jobs:
  release:
    name: Bump versions and create changelog PR --updation
    runs-on: ubuntu-latest
    steps:
      # Check-out repo
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # Check out onto desired branch or tag to create release from
      - name: Checkout tag/branch
        run: git checkout -b release/v${{ github.event.inputs.versionName }}

      # Push changes
      - name: Push new branch
        run: git push origin release/v${{ github.event.inputs.versionName }} 

      # Bump package versions
      - name: Bump package versions
        run: npm run beachball:bump