# Bump package version numbers and create a release branch
name: Automate Release

on:
  push:
    branches:
      - dev
  workflow_dispatch:
    inputs:
      versionName:
        description: 'Name of version '
        required: true
      versionCode:
        description: 'Version #'
        required: true

jobs:
  release:
    name: Bump versions and create changelog PR --updation
    runs-on: ubuntu-latest
    steps:
      
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      # Check-out repo
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # Check out onto desired branch or tag to create release from
      - name: Checkout tag/branch
        run: git checkout -b release/${{ steps.date.outputs.date }}

      # Install node_modules 
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
            cache: 'npm'
      - run: npm ci

      - name: bump package versions
        run: npm run beachball:bump

      - name: git push
        run: |
          git pull 
          git push --set-upstream origin release/${{ steps.date.outputs.date }}

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4.7.2
        with:
          commit_message: "Committing changes to the release branch"

       # Push changes
      - name: Push new branch
        run: git push origin release/${{ steps.date.outputs.date }} 

        # Create PR to master
      - name: Create PR
        run: |
          curl \ 
            -X POST \
            -H 'Accept: application/vnd.github.v3+json' \
            -H 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
            https://api.github.com/repos/AzureAD/microsoft-authentication-library-for-js/pulls \
            -d '{ "title":"${{ steps.date.outputs.date }} release branch merge", "head":"release/${{ steps.date.outputs.date }}", "base":"master", "body":"PR created by the 'automate_release' GitHub action. Please review." }'
            --fail