# Bump package version numbers and create a release branch
name: Automate Release

on:
  push:
    branches:
      - dev
  workflow_dispatch:
    inputs:
      versionName:
        description: 'Name of version '
        required: true
      versionCode:
        description: 'Version #'
        required: true

jobs:
  release:
    name: Bump versions and create changelog PR --updation
    runs-on: ubuntu-latest
    steps:
       
       #get current date
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      # Check-out repo
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Setup bot git information
        run: |
          git config user.email "bmahal@microsoft.com"
          git config user.name "bmahall"

      # Check out onto desired branch or tag to create release from
      - name: Checkout tag/branch
        run: git checkout -b releasev4/${{ steps.date.outputs.date }}

      # Install node_modules here
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
            cache: 'npm'
      - run: npm ci

      - name: bump package versions
        run: npm run beachball:bump

      - name: Retrieve version from package.json
        id: version
        run: |
          ver=$(jq -r .version package.json)
          echo version: $ver

      - name: Commit changes
        run: |
          git add .
          git commit -m "Version bump"

      - name: Push to release branch
        run: git push --set-upstream origin releasev4/${{ steps.date.outputs.date }}


      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4.7.2
        with:
          commit_message: "Committing changes to the release branch:- ${{version}}"
          commit_author: ${{ github.actor }} 
          branch: master