# Bump package version numbers and create a release branch
name: Automate Release

on:
  push:
    branches:
      - dev
  workflow_dispatch:
    inputs:
      versionName:
        description: 'Name of version '
        required: true
      versionCode:
        description: 'Version #'
        required: true

jobs:
  release:
    name: Bump versions and create changelog PR --updation
    runs-on: ubuntu-latest
    steps:
      
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      # Check out onto desired branch or tag to create release from
      - name: Checkout tag/branch
        run: git checkout -b release/${{ steps.date.outputs.date }}

      # Check-out repo
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: release/${{ steps.date.outputs.date }} 


      # Push changes
      - name: Push new branch
        run: git push origin release/${{ steps.date.outputs.date }} 

      # Install node_modules 
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
            cache: 'npm'
      - run: npm ci

      - name: Checkout tag/branch and bump package versions
        run: | 
          git checkout release/${{ steps.date.outputs.date }} 
          npm run beachball:bump

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4.7.2
        with:
          commit_message: "Committing changes to the release branch"

