# Bump package version numbers and create a release branch
name: Automate Release

on:
  push:
    branches:
      - dev
  workflow_dispatch:
    inputs:
      versionName:
        description: 'Name of version '
        required: true
      versionCode:
        description: 'Version #'
        required: true

jobs:
  release:
    name: Bump versions and create changelog PR --updation
    runs-on: ubuntu-latest
    steps:

      - name: Extract Branch Name
        run: echo "BRANCH=$(echo ${GITHUB_REF##*/})" >> $GITHUB_ENV
      
      # Check-out repo
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      

      # Install node_modules  here
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
            cache: 'npm'
      - run: npm ci

      - name: bump package versions
        run: node node_modules/beachball/bin/beachball bump -b origin/dev --bumpDeps false && node release-scripts/updateVersion.js
  

      - name: Step that prints name of pull request's base branch
        run: |
           echo "Pull request's base branch is: ${BASE_BRANCH}"
        env:
              BASE_BRANCH: ${{ github.base_ref }}
        if: github.event_name == 'pull_request'

      - name: Echo out branch values
        run: | 
          echo github.base_ref: ${{ github.base_ref }}
          echo github.head_ref: ${{ github.head_ref }}
          echo github.ref: ${{ github.ref }}
   

      - name: Create Pull Request
        id: pr
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: Release ; version bump; PR->master
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@microsoft.com>
          branch: release-staging
          title: 'Creating PR From :release-staging' 
          body: |
            New release PR
          draft: false

      - name: Step that prints name of pull request's base branch
        run: |
           echo "Pull request's base branch is: ${BASE_BRANCH}"
        env:
              BASE_BRANCH: ${{ github.base_ref }}
        if: github.event_name == 'pull_request'

      - name: Echo out branch values
        run: | 
          echo github.base_ref: ${{ github.base_ref }}
          echo github.head_ref: ${{ github.head_ref }}
          echo github.ref: ${{ github.ref }}
