# Bump package version numbers and create a release branch
name: Automate Release

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch or tag to create release from'
        required: true
        default: 'main'

jobs:
  release:
    name: Bump versions and create changelog PR
    runs-on: ubuntu-latest
    steps:
      # Check-out repo
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # Check out onto desired branch or tag to create release from
      - name: Checkout tag/branch
        run: git checkout ${{ github.event.inputs.branch }}