# https://github.com/dessant/lock-threads
name: 'Lock Closed Issues'

on:
  schedule:
    - cron: '0 2 * * *'

permissions:
  contents: read

jobs:
  lock:
    permissions:
      issues: write  # for dessant/lock-threads to lock issues
    runs-on: ubuntu-latest
    steps:
      - uses: dessant/lock-threads@v2
        with:
          github-token: ${{ github.token }}
          issue-lock-inactive-days: 7
          process-only: 'issues'