# This workflow will triage pull requests and apply a label based on the
# paths that are modified in the pull request.
#
# To use this workflow, you will need to set up a .github/labeler.yml
# file with configuration.  For more information, see:
# https://github.com/actions/labeler/blob/master/README.md

name: Metadata Checker 
on:
  pull_request:
    branches: 
      - dev
  merge_group:
    types: [checks_requested]

concurrency:
  group: metadata-checker-${{github.ref}}
  cancel-in-progress: true

jobs:
  metadata-checker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - uses: actions/cache@v3
      with:
        path: ${{ steps.npm-cache-dir.outputs.dir }}
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Clean Install
      run: npm ci

    - name: Check metadata
      working-directory: lib/msal-common
      run: npm run metadata:check
