# Bump package version numbers and create a release branch
name: Release Packages

on:
  pull_request:
    types: [closed]
    branches:
      - dev

jobs:
  release:
    if: github.event.pull_request.merged == true && !contains(github.head_ref, 'release')
    name: Bump versions and create changelog PR
    runs-on: ubuntu-latest
    env:
      BEACHBALL: 1
      
    steps:
      # Check-out repo
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      # Install node_modules  here
      - name: Use Node.js
        uses: actions/setup-node@v2
        
      - name: Install Beachball
        run: npm ci

      - name: bump package versions
        run: node node_modules/beachball/bin/beachball bump -b origin/dev --bumpDeps false && node release-scripts/updateVersion.js
   
      - name: Create Pull Request
        id: pr
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: Bump package versions
          branch: release-staging
          title: 'Bump package versions for release' 
          body: |
            New release PR
          draft: false

  update_master:
    name: Create PR from dev to master post release 
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && contains(github.head_ref, 'release')
    steps:
      # Check-out repo
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Create Pull Request
        id: pr
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: PR:dev->master post release 
          branch: dev
          base: master
          title: 'Creating PR From :dev to master post release' 
          body: |
            New  PR post-release 
          draft: false
          
  logging:
    name: Logging
    runs-on: ubuntu--latest
    if: github.event.pull_request.merged == true
    steps:
      - name: Head Ref
        env:
          REF: ${{ github.head_ref }}
        run: echo "$REF"
          
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
        
      - name: Print event details
        env:
          GITHUB_EVENT: ${{ toJson(github.event.push) }}
        run: echo "$GITHUB_EVENT"
