name: Mark stale issues and pull requests

on:
  schedule:
  - cron: "0 0 * * *"

jobs:
  stale:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/stale@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'This issue has not seen activity in 14 days. It may be closed if it remains stale.'
        stale-pr-message: 'This PR has not seen activity in 14 days. It may be closed if it remains stale.'
        stale-issue-label: 'no-issue-activity'
        stale-pr-label: 'no-pr-activity'
        exempt-issue-labels: 'internal, feature'
        exempt-pr-labels: 'work-in-progress'
        days-before-stale: 14
        days-before-close: -1
