# Bump package version numbers and create a release branch
name: Update master 

on:
  # the 1st condition
  workflow_run:
    workflows: ["automate_release"]
    types:
      - completed
  pull_request:
    branches: [dev]
    types: [closed]

jobs:
  pr:
    if: ${{ github.event.workflow_run.conclusion == 'success' }} & github.event.pull_request.head.ref == 'release-staging' & github.event.pull_request.merged == true
    
    name: Create PR from dev to master post release 
    runs-on: ubuntu-latest
    steps:

      # Check-out repo
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # Install node_modules here
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
            cache: 'npm'
      - run: npm ci

      #Check-out master
      - run: git checkout master

      
      - name: Create Pull Request
        if: github.event.pull_request.merged == true
        id: pr
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: PR:dev->master post release 
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@microsoft.com>
          branch: dev
          title: 'Creating PR From :dev' 
          body: |
            New  PR post-release 
          draft: false
